applicationName: StartOver
server:
  port: 9000
# NameServer地址 用;作为地址的分隔符
rocketmq:
  namesrvAddr: 119.91.60.86:9876
  # 生产者的组名
  producerId: SyncUser

spring:
  datasource:
    url: jdbc:mysql://gz-cynosdbmysql-grp-fgolqupl.sql.tencentcdb.com:22172/rocketmq?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 2EZ4vino!
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB

# 配置mybatis-plus
mybatis-plus:
  # 配置扫描xml
  mapper-locations: classpath:mapper/*.xml
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.willjo.dal.entity